# Generated by Django 3.1.2 on 2020-11-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullname',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_artisan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Rasheed', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(default='Rasheed', max_length=15),
            preserve_default=False,
        ),
    ]
