# Generated by Django 3.1.2 on 2020-11-04 16:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='video',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='videos')),
                ('title', models.CharField(max_length=30)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.content')),
            ],
        ),
    ]
