# Generated by Django 3.1.2 on 2020-11-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_video_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='content',
        ),
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
