# Generated by Django 3.1.2 on 2020-11-05 16:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20201105_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='course',
            name='videos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='videos'), blank=True, null=True, size=None),
        ),
    ]
