# Generated by Django 3.1.2 on 2020-11-05 16:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20201105_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='videos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='files'), blank=True, null=True, size=None),
        ),
    ]
