# Generated by Django 3.1.2 on 2020-11-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20201106_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
