# Generated by Django 3.1.2 on 2020-11-07 09:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_course_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_course',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
