# Generated by Django 3.1.2 on 2020-11-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_user_my_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_course',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
