# Generated by Django 3.1.2 on 2020-11-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20201107_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='plan',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(blank=True, choices=[('foundation', 'Foundation'), ('intermediate', 'Intermediate'), ('enterprise', 'Enterprise')], max_length=300, null=True),
        ),
    ]
