# Generated by Django 3.1.2 on 2020-11-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20201108_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='plan',
            field=models.CharField(default='foundation', max_length=300),
        ),
    ]
